// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Builder.Template.CSharp.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Junior\Projetos\GITHUB.COM\thiagosanches\builder\Builder.Template.CSharp\Template\SolutionTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class SolutionTemplate : SolutionTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\nMicrosoft Visual Studio Solution File, Format Version 12.00\r\n# Visual Studio 20" +
                    "13\r\nVisualStudioVersion = 12.0.31101.0\r\nMinimumVisualStudioVersion = 10.0.40219." +
                    "1\r\n\r\n");
            
            #line 14 "D:\Junior\Projetos\GITHUB.COM\thiagosanches\builder\Builder.Template.CSharp\Template\SolutionTemplate.tt"
 if (__app__.ProjectCollection.Projects.Count() > 0) { 
            
            #line default
            #line hidden
            
            #line 15 "D:\Junior\Projetos\GITHUB.COM\thiagosanches\builder\Builder.Template.CSharp\Template\SolutionTemplate.tt"
 foreach (var project in __app__.ProjectCollection.Projects) { 
            
            #line default
            #line hidden
            this.Write("Project(\"");
            
            #line 16 "D:\Junior\Projetos\GITHUB.COM\thiagosanches\builder\Builder.Template.CSharp\Template\SolutionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(@__app__.Guid));
            
            #line default
            #line hidden
            this.Write("\") = \"");
            
            #line 16 "D:\Junior\Projetos\GITHUB.COM\thiagosanches\builder\Builder.Template.CSharp\Template\SolutionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(project.Name));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 16 "D:\Junior\Projetos\GITHUB.COM\thiagosanches\builder\Builder.Template.CSharp\Template\SolutionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(@__app__.GetRelativePathToSolution(project)));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 16 "D:\Junior\Projetos\GITHUB.COM\thiagosanches\builder\Builder.Template.CSharp\Template\SolutionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(project.Guid));
            
            #line default
            #line hidden
            this.Write("\"\r\nEndProject\r\n");
            
            #line 18 "D:\Junior\Projetos\GITHUB.COM\thiagosanches\builder\Builder.Template.CSharp\Template\SolutionTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 19 "D:\Junior\Projetos\GITHUB.COM\thiagosanches\builder\Builder.Template.CSharp\Template\SolutionTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\nGlobal\r\n\tGlobalSection(SolutionConfigurationPlatforms) = preSolution\r\n\t\tDebug|A" +
                    "ny CPU = Debug|Any CPU\r\n\t\tRelease|Any CPU = Release|Any CPU\r\n\tEndGlobalSection\r\n" +
                    "\tGlobalSection(ProjectConfigurationPlatforms) = postSolution\r\n\t\t{3DED97EA-4375-4" +
                    "C2D-BDF3-2C7B7DA0B052}.Debug|Any CPU.ActiveCfg = Debug|Any CPU\r\n\t\t{3DED97EA-4375" +
                    "-4C2D-BDF3-2C7B7DA0B052}.Debug|Any CPU.Build.0 = Debug|Any CPU\r\n\t\t{3DED97EA-4375" +
                    "-4C2D-BDF3-2C7B7DA0B052}.Release|Any CPU.ActiveCfg = Release|Any CPU\r\n\t\t{3DED97E" +
                    "A-4375-4C2D-BDF3-2C7B7DA0B052}.Release|Any CPU.Build.0 = Release|Any CPU\r\n\t\t{A1E" +
                    "A124F-46F2-4E08-84CB-741831363D75}.Debug|Any CPU.ActiveCfg = Debug|Any CPU\r\n\t\t{A" +
                    "1EA124F-46F2-4E08-84CB-741831363D75}.Debug|Any CPU.Build.0 = Debug|Any CPU\r\n\t\t{A" +
                    "1EA124F-46F2-4E08-84CB-741831363D75}.Release|Any CPU.ActiveCfg = Release|Any CPU" +
                    "\r\n\t\t{A1EA124F-46F2-4E08-84CB-741831363D75}.Release|Any CPU.Build.0 = Release|Any" +
                    " CPU\r\n\t\t{F5DC5E41-0AE6-4811-8105-4A48A1DD2C0D}.Debug|Any CPU.ActiveCfg = Debug|A" +
                    "ny CPU\r\n\t\t{F5DC5E41-0AE6-4811-8105-4A48A1DD2C0D}.Debug|Any CPU.Build.0 = Debug|A" +
                    "ny CPU\r\n\t\t{F5DC5E41-0AE6-4811-8105-4A48A1DD2C0D}.Release|Any CPU.ActiveCfg = Rel" +
                    "ease|Any CPU\r\n\t\t{F5DC5E41-0AE6-4811-8105-4A48A1DD2C0D}.Release|Any CPU.Build.0 =" +
                    " Release|Any CPU\r\n\t\t{0235F1D9-6904-46F1-8798-92FFBF8B0A35}.Debug|Any CPU.ActiveC" +
                    "fg = Debug|Any CPU\r\n\t\t{0235F1D9-6904-46F1-8798-92FFBF8B0A35}.Debug|Any CPU.Build" +
                    ".0 = Debug|Any CPU\r\n\t\t{0235F1D9-6904-46F1-8798-92FFBF8B0A35}.Release|Any CPU.Act" +
                    "iveCfg = Release|Any CPU\r\n\t\t{0235F1D9-6904-46F1-8798-92FFBF8B0A35}.Release|Any C" +
                    "PU.Build.0 = Release|Any CPU\r\n\t\t{552CCB8D-DA2F-4C0A-8AD5-2277DDDB9DCC}.Debug|Any" +
                    " CPU.ActiveCfg = Debug|Any CPU\r\n\t\t{552CCB8D-DA2F-4C0A-8AD5-2277DDDB9DCC}.Debug|A" +
                    "ny CPU.Build.0 = Debug|Any CPU\r\n\t\t{552CCB8D-DA2F-4C0A-8AD5-2277DDDB9DCC}.Release" +
                    "|Any CPU.ActiveCfg = Release|Any CPU\r\n\t\t{552CCB8D-DA2F-4C0A-8AD5-2277DDDB9DCC}.R" +
                    "elease|Any CPU.Build.0 = Release|Any CPU\r\n\t\t{A21DB1AD-5276-4C1D-ACB3-E9C72151A28" +
                    "B}.Debug|Any CPU.ActiveCfg = Debug|Any CPU\r\n\t\t{A21DB1AD-5276-4C1D-ACB3-E9C72151A" +
                    "28B}.Debug|Any CPU.Build.0 = Debug|Any CPU\r\n\t\t{A21DB1AD-5276-4C1D-ACB3-E9C72151A" +
                    "28B}.Release|Any CPU.ActiveCfg = Release|Any CPU\r\n\t\t{A21DB1AD-5276-4C1D-ACB3-E9C" +
                    "72151A28B}.Release|Any CPU.Build.0 = Release|Any CPU\r\n\t\t{53F70169-ECDA-4328-BE9F" +
                    "-BAAE821FB12E}.Debug|Any CPU.ActiveCfg = Debug|Any CPU\r\n\t\t{53F70169-ECDA-4328-BE" +
                    "9F-BAAE821FB12E}.Debug|Any CPU.Build.0 = Debug|Any CPU\r\n\t\t{53F70169-ECDA-4328-BE" +
                    "9F-BAAE821FB12E}.Release|Any CPU.ActiveCfg = Release|Any CPU\r\n\t\t{53F70169-ECDA-4" +
                    "328-BE9F-BAAE821FB12E}.Release|Any CPU.Build.0 = Release|Any CPU\r\n\tEndGlobalSect" +
                    "ion\r\n\tGlobalSection(SolutionProperties) = preSolution\r\n\t\tHideSolutionNode = FALS" +
                    "E\r\n\tEndGlobalSection\r\nEndGlobal");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "D:\Junior\Projetos\GITHUB.COM\thiagosanches\builder\Builder.Template.CSharp\Template\SolutionTemplate.tt"

private global::Builder.Dispatcher.Application ___app__Field;

/// <summary>
/// Access the __app__ parameter of the template.
/// </summary>
private global::Builder.Dispatcher.Application @__app__
{
    get
    {
        return this.___app__Field;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool @__app__ValueAcquired = false;
if (this.Session.ContainsKey("__app__"))
{
    this.___app__Field = ((global::Builder.Dispatcher.Application)(this.Session["__app__"]));
    @__app__ValueAcquired = true;
}
if ((@__app__ValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("__app__");
    if ((data != null))
    {
        this.___app__Field = ((global::Builder.Dispatcher.Application)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class SolutionTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
